### PR TITLE
Add box sphere intersection

### PR DESCRIPTION
**Pull request by hongkai-dai**
Still working on the code to compute cos(theta), but I think it can help if I send this PR first.

---
This change is [Reviewable](https://reviewable.io/reviews/russtedrake/drake/30)

### CODE REVIEW

**Comment by RussTedrake** [comment]
Reviewed 3 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/rotation_constraint.cc, line 325 at r1](https://reviewable.io:443/reviews/russtedrake/drake/30#-Kbj9cVP6__JTHmlWbwv:-Kbj9cVQ-zReUQ9c1nId:b-v8kr55) ([raw file](https://github.com/russtedrake/drake/blob/99ed0a657d47d78a8e27ebd3d9b3f6faa192fe14/drake/solvers/rotation_constraint.cc#L325)):*
> ```cpp
>       pt_farther(axis) = bmax(axis);
>       pt_closer(fixed_axis1) =
>           i & (1 << 1) ? bmin(fixed_axis1) : bmax(fixed_axis1);
> ```

btw - this logic looks correct, but in this case it would probably be much cleaner to just use nested for loops (i,j both going 0,1, or even loop on the double values).

---

*[drake/solvers/rotation_constraint.cc, line 395 at r1](https://reviewable.io:443/reviews/russtedrake/drake/30#-KbjBV8krNg58eL9ObQ1:-KbjBV8krNg58eL9ObQ2:b-jysydi) ([raw file](https://github.com/russtedrake/drake/blob/99ed0a657d47d78a8e27ebd3d9b3f6faa192fe14/drake/solvers/rotation_constraint.cc#L395)):*
> ```cpp
>                                                                       box_max);
>             DRAKE_DEMAND(pts.size() >= 3);
>             // Set normal to be the average of pts.
> ```

btw -- that's a change, but is probably reasonable.

---

*[drake/solvers/rotation_constraint.cc, line 408 at r1](https://reviewable.io:443/reviews/russtedrake/drake/30#-KbjAiZgncJFAj1utccv:-KbjAiZhP3g23Kn3u94J:bg1mttp) ([raw file](https://github.com/russtedrake/drake/blob/99ed0a657d47d78a8e27ebd3d9b3f6faa192fe14/drake/solvers/rotation_constraint.cc#L408)):*
> ```cpp
>             // point between the unit circle and the box. Notice that the
>             // intersection between the box and the unit circle can be
>             // decomposed
> ```

bad line break.  and the grammar should be "decomposed into segments, were each segment is a curve that connects one .. edge of the box to another ... of the box."   (there are too many commas and a few incorrect words)

---

*[drake/solvers/rotation_constraint.cc, line 413 at r1](https://reviewable.io:443/reviews/russtedrake/drake/30#-KbjCAPZm5MLt1wUM2Ud:-KbjCAPZm5MLt1wUM2Ue:bxshmrf) ([raw file](https://github.com/russtedrake/drake/blob/99ed0a657d47d78a8e27ebd3d9b3f6faa192fe14/drake/solvers/rotation_constraint.cc#L413)):*
> ```cpp
>             // intersecting point on the edge of the box.
>             // Take one curve as an example, that
>             // connects the points v1, v2, on different edges of the box, and
> ```

bad line break.

---

*[drake/solvers/rotation_constraint.cc, line 418 at r1](https://reviewable.io:443/reviews/russtedrake/drake/30#-KbjCWnDx6Th6JAPW8nz:-KbjCWnDx6Th6JAPW8o-:b-7s4tn4) ([raw file](https://github.com/russtedrake/drake/blob/99ed0a657d47d78a8e27ebd3d9b3f6faa192fe14/drake/solvers/rotation_constraint.cc#L418)):*
> ```cpp
>             // The point v on the curve can be written as
>             // v(i) = u, v(j)² + v(k)² = 1 - u²,
>             // min(v1(j), v2(j)) <= v(j) <= max(v1(j), v2(j))
> ```

comma

---

*[drake/solvers/rotation_constraint.cc, line 428 at r1](https://reviewable.io:443/reviews/russtedrake/drake/30#-KbjCsIMALfeeeVDck6z:-KbjCsINetMNxnqGq4F1:baixi98) ([raw file](https://github.com/russtedrake/drake/blob/99ed0a657d47d78a8e27ebd3d9b3f6faa192fe14/drake/solvers/rotation_constraint.cc#L428)):*
> ```cpp
>             // since normal(j) >= 0, normal(k) >= 0,
>             // we know that the minimal of this function is obtained at the
>             // boundary of α.
> ```

btw - nice!

that should be true for any choice of normal inside the box.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/russtedrake/drake/30)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/rotation_constraint.cc, line 428 at r1](https://reviewable.io:443/reviews/russtedrake/drake/30#-KbjCsIMALfeeeVDck6z:-KbkLYmmUjiTJojL6Zwt:b-f55kh5) ([raw file](https://github.com/russtedrake/drake/blob/99ed0a657d47d78a8e27ebd3d9b3f6faa192fe14/drake/solvers/rotation_constraint.cc#L428)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw - nice!

that should be true for any choice of normal inside the box.  
</blockquote></details>

I realized we can solve an SOCP to find the normal, that has the tightest theta. I will update this part to find the normal vector.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/russtedrake/drake/30)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/rotation_constraint.cc, line 325 at r1](https://reviewable.io:443/reviews/russtedrake/drake/30#-Kbj9cVP6__JTHmlWbwv:-KbkfzmONVLfHfZV12pr:b-896fix) ([raw file](https://github.com/russtedrake/drake/blob/99ed0a657d47d78a8e27ebd3d9b3f6faa192fe14/drake/solvers/rotation_constraint.cc#L325)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw - this logic looks correct, but in this case it would probably be much cleaner to just use nested for loops (i,j both going 0,1, or even loop on the double values).
</blockquote></details>

Done.

---

*[drake/solvers/rotation_constraint.cc, line 395 at r1](https://reviewable.io:443/reviews/russtedrake/drake/30#-KbjBV8krNg58eL9ObQ1:-KbkeQyoQQX88D8NYd2f:b-nf22lh) ([raw file](https://github.com/russtedrake/drake/blob/99ed0a657d47d78a8e27ebd3d9b3f6faa192fe14/drake/solvers/rotation_constraint.cc#L395)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

btw -- that's a change, but is probably reasonable.
</blockquote></details>

Done. I rewrite this part to find the normal that gives the tightest bound.

---

*[drake/solvers/rotation_constraint.cc, line 408 at r1](https://reviewable.io:443/reviews/russtedrake/drake/30#-KbjAiZgncJFAj1utccv:-KbkeWCZ9SjyqNktLUQG:b-896fix) ([raw file](https://github.com/russtedrake/drake/blob/99ed0a657d47d78a8e27ebd3d9b3f6faa192fe14/drake/solvers/rotation_constraint.cc#L408)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

bad line break.  and the grammar should be "decomposed into segments, were each segment is a curve that connects one .. edge of the box to another ... of the box."   (there are too many commas and a few incorrect words)
</blockquote></details>

Done.

---

*[drake/solvers/rotation_constraint.cc, line 413 at r1](https://reviewable.io:443/reviews/russtedrake/drake/30#-KbjCAPZm5MLt1wUM2Ud:-KbkeWut95oPs365_wuV:b-896fix) ([raw file](https://github.com/russtedrake/drake/blob/99ed0a657d47d78a8e27ebd3d9b3f6faa192fe14/drake/solvers/rotation_constraint.cc#L413)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

bad line break.
</blockquote></details>

Done.

---

*[drake/solvers/rotation_constraint.cc, line 418 at r1](https://reviewable.io:443/reviews/russtedrake/drake/30#-KbjCWnDx6Th6JAPW8nz:-KbkeXakIQ5fHlRqTF_6:b-896fix) ([raw file](https://github.com/russtedrake/drake/blob/99ed0a657d47d78a8e27ebd3d9b3f6faa192fe14/drake/solvers/rotation_constraint.cc#L418)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

comma
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/russtedrake/drake/30)*

**Comment by RussTedrake** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/rotation_constraint.cc, line 395 at r1](https://reviewable.io:443/reviews/russtedrake/drake/30#-KbjBV8krNg58eL9ObQ1:-KblDfkknu8OwDyOVsNZ:b-cst1bm) ([raw file](https://github.com/russtedrake/drake/blob/99ed0a657d47d78a8e27ebd3d9b3f6faa192fe14/drake/solvers/rotation_constraint.cc#L395)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Done. I rewrite this part to find the normal that gives the tightest bound.
</blockquote></details>

nice.  did the setup time increase substantially?

---

*[drake/solvers/rotation_constraint.cc, line 425 at r2](https://reviewable.io:443/reviews/russtedrake/drake/30#-KblEB1AH8azY-o8WAY1:-KblEB1AH8azY-o8WAY2:bc6yv59) ([raw file](https://github.com/russtedrake/drake/blob/3d6951cdc73c02c0fe49fdb0bd68a5b673866afb/drake/solvers/rotation_constraint.cc#L425)):*
> ```cpp
>             // To find the tightest bound d satisfying nᵀ * v >= d for all
>             // vector v in the intersection region, we use the fact that for
>             // a given normal vector v, the minimal of nᵀ * v is always obtained
> ```

normal vector n (not v)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/russtedrake/drake/30)*

**Comment by hongkai-dai** [comment]
Just pushed the change to test the SOCP result, by using the non-socp version as the lower bound.

---

Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/russtedrake/drake/30#-:-Kbm6-csYLLsYzqv3k4k:b-vog3mu)*

**Comment by hongkai-dai** [comment]
Review status: 0 of 3 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/solvers/rotation_constraint.cc, line 425 at r2](https://reviewable.io:443/reviews/russtedrake/drake/30#-KblEB1AH8azY-o8WAY1:-Kbm6GN6-1uLV0gnoHpw:b-896fix) ([raw file](https://github.com/russtedrake/drake/blob/3d6951cdc73c02c0fe49fdb0bd68a5b673866afb/drake/solvers/rotation_constraint.cc#L425)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

normal vector n (not v)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/russtedrake/drake/30)*

**Comment by RussTedrake** [comment]
very nice!  :lgtm: (just the one typo -- which I tried to edit myself but could not)

---

Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/test/rotation_constraint_test.cc, line 204 at r3](https://reviewable.io:443/reviews/russtedrake/drake/30#-KbmBtt7zzngmVAdxS3o:-KbmBtt7zzngmVAdxS3p:bvqliii) ([raw file](https://github.com/russtedrake/drake/blob/12497348d78d0701f4378d533c575310af4074fe/drake/solvers/test/rotation_constraint_test.cc#L204)):*
> ```cpp
> void CompareHalfspaceRelaxation(const std::vector<Vector3d>& pts) {
>   // Computes a possibly less tight n and d analytically. For each triangle with
>   // vertices pts[i], pts[j] and pts[k], determine if the halfspace coincinding
> ```

coinciding

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/russtedrake/drake/30#-:-KbmCFADe8kVy3ksa-cX:b-i88rir)*

**Comment by hongkai-dai** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[drake/solvers/test/rotation_constraint_test.cc, line 204 at r3](https://reviewable.io:443/reviews/russtedrake/drake/30#-KbmBtt7zzngmVAdxS3o:-KbmNNMFDu3w_geQcgLW:b-896fix) ([raw file](https://github.com/russtedrake/drake/blob/12497348d78d0701f4378d533c575310af4074fe/drake/solvers/test/rotation_constraint_test.cc#L204)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

coinciding
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/russtedrake/drake/30)*

**Pull request merged**
